/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.6.1/userguide/multi_project_builds.html
 */

rootProject.name = "upgraded-octo-guacamole"

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            alias("groovy-core").to("org.codehaus.groovy:groovy:3.0.5")
            alias("groovy-json").to("org.codehaus.groovy:groovy-json:3.0.5")
            alias("groovy-nio").to("org.codehaus.groovy:groovy-nio:3.0.5")
            alias("commons-lang3").to("org.apache.commons", "commons-lang3").version {
                strictly("[3.8, 4.0[")
                prefer("3.9")
            }
        }
    }
}