/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package upgraded.octo.guacamole

import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.initialization.Settings

/**
 * A simple 'hello world' plugin.
 */
class UpgradedOctoGuacamolePlugin: Plugin<Settings> {
    override fun apply(settings: Settings) {
        settings.dependencyResolutionManagement {
//            versionCatalogs.create("libs") {
//                //                create("libs") {
//                alias("groovy-core").to("org.codehaus.groovy:groovy:3.0.5")
//                //                    alias("groovy-json").to("org.codehaus.groovy:groovy-json:3.0.5")
//                //                    alias("groovy-nio").to("org.codehaus.groovy:groovy-nio:3.0.5")
//                //                    alias("commons-lang3").to("org.apache.commons", "commons-lang3").version {
//                //                        strictly("[3.8, 4.0[")
//                //                        prefer("3.9")
//                //                    }
//                //                }
//                //            }
//            }
        }
    }
}
