[dependencies]
anim = "org.apache.xmlgraphics:batik-anim:1.13"
awtUtil = "org.apache.xmlgraphics:batik-awt-util:1.13"
bridge = "org.apache.xmlgraphics:batik-bridge:1.13"
codec = "org.apache.xmlgraphics:batik-codec:1.13"
constants = "org.apache.xmlgraphics:batik-constants:1.13"
css = "org.apache.xmlgraphics:batik-css:1.13"
dom = "org.apache.xmlgraphics:batik-dom:1.13"
ext = "org.apache.xmlgraphics:batik-ext:1.13"
extension = "org.apache.xmlgraphics:batik-extension:1.13"
guiUtil = "org.apache.xmlgraphics:batik-gui-util:1.13"
gvt = "org.apache.xmlgraphics:batik-gvt:1.13"
i18n = "org.apache.xmlgraphics:batik-i18n:1.13"
parser = "org.apache.xmlgraphics:batik-parser:1.13"
rasterizer = "org.apache.xmlgraphics:batik-rasterizer:1.13"
rasterizerExt = "org.apache.xmlgraphics:batik-rasterizer-ext:1.13"
script = "org.apache.xmlgraphics:batik-script:1.13"
slideshow = "org.apache.xmlgraphics:batik-slideshow:1.13"
squiggle = "org.apache.xmlgraphics:batik-squiggle:1.13"
squiggleExt = "org.apache.xmlgraphics:batik-squiggle-ext:1.13"
svgDom = "org.apache.xmlgraphics:batik-svg-dom:1.13"
svggen = "org.apache.xmlgraphics:batik-svggen:1.13"
svgpp = "org.apache.xmlgraphics:batik-svgpp:1.13"
swing = "org.apache.xmlgraphics:batik-swing:1.13"
transcoder = "org.apache.xmlgraphics:batik-transcoder:1.13"
ttf2svg = "org.apache.xmlgraphics:batik-ttf2svg:1.13"
util = "org.apache.xmlgraphics:batik-util:1.13"
xml = "org.apache.xmlgraphics:batik-xml:1.13"
xmlgraphicsCommons = "org.apache.xmlgraphics:xmlgraphics-commons:2.4"
