[dependencies]
h5JLoaderPlugin = "org.janelia:H5J_Loader_Plugin:1.1.0"
sNT = "org.morphonets:SNT:3.1.112"
jitkTps = "jitk:jitk-tps:3.0.1"
mpicbg = "mpicbg:mpicbg:1.4.1"
mpicbg = "mpicbg:mpicbg_:1.4.1"
morphoLibJ = "fr.inra.ijpb:MorphoLibJ_:1.4.2.1"
bigStitcher = "net.preibisch:BigStitcher:0.5.8"
multiviewReconstruction = "net.preibisch:multiview-reconstruction:0.7.2"
multiviewSimulation = "net.preibisch:multiview-simulation:0.2.0"
coremem = "net.clearcontrol:coremem:0.4.8"
cleargl = "net.clearvolume:cleargl:2.2.10"
scenery = "graphics.scenery:scenery:0.7.0-beta-7"
sciview = "sc.iview:sciview:0.2.0-beta-5"
awsJavaSdkS3 = "com.amazonaws:aws-java-sdk-s3:1.11.796"
mavenArtifactTransfer = "org.apache.maven.shared:maven-artifact-transfer:0.12.0"
mavenCommonArtifactFilters = "org.apache.maven.shared:maven-common-artifact-filters:3.1.0"
mavenCore = "org.apache.maven:maven-core:3.6.3"
mavenPluginToolsApi = "org.apache.maven.plugin-tools:maven-plugin-tools-api:3.6.0"
sisuInjectBean = "org.sonatype.sisu:sisu-inject-bean:2.6.0"
sisuInjectPlexus = "org.sonatype.sisu:sisu-inject-plexus:2.6.0"
poi = "org.apache.poi:poi:3.17"
sparkCore211 = "org.apache.spark:spark-core_2.11:2.3.1"
httpclient = "org.apache.httpcomponents:httpclient:4.5.12"
httpcore = "org.apache.httpcomponents:httpcore:4.4.13"
jblosc = "org.lasersonlab:jblosc:1.0.1"
cdiApi = "javax.enterprise:cdi-api:1.2"
commonsBeanutils = "commons-beanutils:commons-beanutils:1.9.4"
commonsCodec = "commons-codec:commons-codec:1.14"
commonsCollections = "commons-collections:commons-collections:3.2.2"
commonsCompress = "org.apache.commons:commons-compress:1.20"
commonsIo = "commons-io:commons-io:2.7"
commonsLang = "commons-lang:commons-lang:2.6"
commonsLang3 = "org.apache.commons:commons-lang3:3.10"
commonsLogging = "commons-logging:commons-logging:1.2"
commonsMath3 = "org.apache.commons:commons-math3:3.6.1"
commonsText = "org.apache.commons:commons-text:1.8"
cglib = "cglib:cglib:3.3.0"
eclipseCollections = "org.eclipse.collections:eclipse-collections:10.4.0"
eclipseCollectionsApi = "org.eclipse.collections:eclipse-collections-api:10.4.0"
eclipseCollectionsForkjoin = "org.eclipse.collections:eclipse-collections-forkjoin:10.4.0"
eclipseCollectionsTestutils = "org.eclipse.collections:eclipse-collections-testutils:10.4.0"
googleCloudNio = "com.google.cloud:google-cloud-nio:0.120.0-alpha"
googleCloudResourcemanager = "com.google.cloud:google-cloud-resourcemanager:0.117.2-alpha"
googleCloudStorage = "com.google.cloud:google-cloud-storage:1.108.0"
gson = "com.google.code.gson:gson:2.8.6"
guava = "com.google.guava:guava:21.0"
hsqldb = "hsqldb:hsqldb:1.8.0.10"
itextpdf = "com.itextpdf:itextpdf:5.5.13.1"
jackrabbitWebdav = "org.apache.jackrabbit:jackrabbit-webdav:2.21.1"
jacksonDatabind = "com.fasterxml.jackson.core:jackson-databind:2.11.0"
jaiCodec = "com.sun.media:jai-codec:1.1.3"
jaiCore = "javax.media:jai-core:1.1.3"
jama = "gov.nist.math:jama:1.0.3"
javassist = "org.javassist:javassist:3.27.0-GA"
jdom2 = "org.jdom:jdom2:2.0.6"
jfreechart = "org.jfree:jfreechart:1.5.0"
jfreesvg = "org.jfree:jfreesvg:3.4"
jgraphtCore = "org.jgrapht:jgrapht-core:1.4.0"
jgraphtDemo = "org.jgrapht:jgrapht-demo:1.4.0"
jgraphtExt = "org.jgrapht:jgrapht-ext:1.4.0"
jgraphtGuava = "org.jgrapht:jgrapht-guava:1.4.0"
jgraphtIo = "org.jgrapht:jgrapht-io:1.4.0"
jgraphtOpt = "org.jgrapht:jgrapht-opt:1.4.0"
jgraphx = "com.github.vlsi.mxgraph:jgraphx:4.1.0"
jhdf5 = "cisd:jhdf5:14.12.6"
jna = "net.java.dev.jna:jna:4.5.2"
jodaTime = "joda-time:joda-time:2.10.6"
gluegenRtMain = "org.jogamp.gluegen:gluegen-rt-main:2.3.2"
joalMain = "org.jogamp.joal:joal-main:2.3.2"
joclMain = "org.jogamp.jocl:jocl-main:2.3.2"
joglAllMain = "org.jogamp.jogl:jogl-all-main:2.3.2"
joml = "org.joml:joml:1.9.25"
jpedalSTD = "org.jpedal:jpedalSTD:2.80b11"
jsch = "com.jcraft:jsch:0.1.55"
jythonSlim = "org.python:jython-slim:2.7.2"
jzlib = "com.jcraft:jzlib:1.1.3"
logbackClassic = "ch.qos.logback:logback-classic:1.2.3"
logbackCore = "ch.qos.logback:logback-core:1.2.3"
lz4Java = "org.lz4:lz4-java:1.7.1"
mapdb = "org.mapdb:mapdb:3.0.8"
miglayoutCore = "com.miglayout:miglayout-core:5.2"
miglayoutSwing = "com.miglayout:miglayout-swing:5.2"
miglayoutSwt = "com.miglayout:miglayout-swt:5.2"
minesJtk = "edu.mines:mines-jtk:20151125"
ojalgo = "org.ojalgo:ojalgo:45.1.1"
opencsv = "com.opencsv:opencsv:5.2"
picocli = "info.picocli:picocli:4.3.2"
postgresql = "org.postgresql:postgresql:42.2.12"
rsyntaxtextarea = "com.fifesoft:rsyntaxtextarea:3.1.1"
autocomplete = "com.fifesoft:autocomplete:3.1.0"
languagesupport = "com.fifesoft:languagesupport:3.1.0"
slf4jApi = "org.slf4j:slf4j-api:1.7.30"
slf4jExt = "org.slf4j:slf4j-ext:1.7.30"
slf4jJcl = "org.slf4j:slf4j-jcl:1.7.30"
slf4jJdk14 = "org.slf4j:slf4j-jdk14:1.7.30"
slf4jNop = "org.slf4j:slf4j-nop:1.7.30"
slf4jSimple = "org.slf4j:slf4j-simple:1.7.30"
jclOverSlf4j = "org.slf4j:jcl-over-slf4j:1.7.30"
snakeyaml = "org.yaml:snakeyaml:1.26"
snakeyamlEngine = "org.snakeyaml:snakeyaml-engine:2.1"
springAop = "org.springframework:spring-aop:3.2.9.RELEASE"
tensorflow = "org.tensorflow:tensorflow:1.12.0"
libtensorflow = "org.tensorflow:libtensorflow:1.12.0"
libtensorflowJni = "org.tensorflow:libtensorflow_jni:1.12.0"
libtensorflowJniGpu = "org.tensorflow:libtensorflow_jni_gpu:1.12.0"
proto = "org.tensorflow:proto:1.12.0"
trove4j = "net.sf.trove4j:trove4j:3.0.3"
wekaDev = "nz.ac.waikato.cms.weka:weka-dev:3.9.4"
xz = "org.tukaani:xz:1.8"
junit = "junit:junit:4.13"
junitJupiterApi = "org.junit.jupiter:junit-jupiter-api:5.6.2"
junitJupiterEngine = "org.junit.jupiter:junit-jupiter-engine:5.6.2"
junitJupiterMigrationsupport = "org.junit.jupiter:junit-jupiter-migrationsupport:5.6.2"
junitJupiterParams = "org.junit.jupiter:junit-jupiter-params:5.6.2"
junitVintageEngine = "org.junit.vintage:junit-vintage-engine:5.6.2"
jmockit = "org.jmockit:jmockit:1.49"
mockitoCore = "org.mockito:mockito-core:2.19.0"
jmhCore = "org.openjdk.jmh:jmh-core:1.23"
jmhGeneratorAnnprocess = "org.openjdk.jmh:jmh-generator-annprocess:1.23"
