[dependencies]
jettyAnnotations = "org.eclipse.jetty:jetty-annotations:9.4.29.v20200521"
jettyClient = "org.eclipse.jetty:jetty-client:9.4.29.v20200521"
jettyContinuation = "org.eclipse.jetty:jetty-continuation:9.4.29.v20200521"
jettyDeploy = "org.eclipse.jetty:jetty-deploy:9.4.29.v20200521"
jettyHttp = "org.eclipse.jetty:jetty-http:9.4.29.v20200521"
jettyHttpSpi = "org.eclipse.jetty:jetty-http-spi:9.4.29.v20200521"
jettyIo = "org.eclipse.jetty:jetty-io:9.4.29.v20200521"
jettyJaas = "org.eclipse.jetty:jetty-jaas:9.4.29.v20200521"
jettyJaspi = "org.eclipse.jetty:jetty-jaspi:9.4.29.v20200521"
jettyJmx = "org.eclipse.jetty:jetty-jmx:9.4.29.v20200521"
jettyJndi = "org.eclipse.jetty:jetty-jndi:9.4.29.v20200521"
jettyNosql = "org.eclipse.jetty:jetty-nosql:9.4.29.v20200521"
jettyPlus = "org.eclipse.jetty:jetty-plus:9.4.29.v20200521"
jettyProxy = "org.eclipse.jetty:jetty-proxy:9.4.29.v20200521"
jettyRewrite = "org.eclipse.jetty:jetty-rewrite:9.4.29.v20200521"
jettySecurity = "org.eclipse.jetty:jetty-security:9.4.29.v20200521"
jettyServer = "org.eclipse.jetty:jetty-server:9.4.29.v20200521"
jettyServlet = "org.eclipse.jetty:jetty-servlet:9.4.29.v20200521"
jettyServlets = "org.eclipse.jetty:jetty-servlets:9.4.29.v20200521"
jettySpring = "org.eclipse.jetty:jetty-spring:9.4.29.v20200521"
jettyStart = "org.eclipse.jetty:jetty-start:9.4.29.v20200521"
jettyUtil = "org.eclipse.jetty:jetty-util:9.4.29.v20200521"
jettyUtilAjax = "org.eclipse.jetty:jetty-util-ajax:9.4.29.v20200521"
jettyWebapp = "org.eclipse.jetty:jetty-webapp:9.4.29.v20200521"
jettyXml = "org.eclipse.jetty:jetty-xml:9.4.29.v20200521"
