[dependencies]
 = "sc.fiji:fiji:2.2.0"
analyzeSkeleton = "sc.fiji:AnalyzeSkeleton_:3.4.2"
anisotropicDiffusion2D = "sc.fiji:Anisotropic_Diffusion_2D:2.0.1"
archipelagoPlugins = "sc.fiji:Archipelago_Plugins:0.5.4"
arrow = "sc.fiji:Arrow_:2.0.2"
autoLocalThreshold = "sc.fiji:Auto_Local_Threshold:1.10.1"
autoThreshold = "sc.fiji:Auto_Threshold:1.17.2"
balloonSegmentation = "sc.fiji:BalloonSegmentation_:3.0.1"
bugSubmitter = "sc.fiji:Bug_Submitter:2.1.1"
cPUMeter = "sc.fiji:CPU_Meter:2.0.1"
calculatorPlus = "sc.fiji:Calculator_Plus:2.0.1"
cellCounter = "sc.fiji:Cell_Counter:3.0.0"
colocalisationAnalysis = "sc.fiji:Colocalisation_Analysis:3.0.5"
colorHistogram = "sc.fiji:Color_Histogram:2.0.7"
colorInspector3D = "sc.fiji:Color_Inspector_3D:2.5.0"
colourDeconvolution = "sc.fiji:Colour_Deconvolution:3.0.3"
correctBleach = "sc.fiji:CorrectBleach_:2.0.3"
correct3DDrift = "sc.fiji:Correct_3D_Drift:1.0.6"
descriptorBasedRegistration = "sc.fiji:Descriptor_based_registration:2.1.7"
dichromacy = "sc.fiji:Dichromacy_:2.1.2"
directionality = "sc.fiji:Directionality_:2.3.0"
fSAlignTrakEM2 = "sc.fiji:FS_Align_TrakEM2:2.0.3"
featureDetection = "sc.fiji:Feature_Detection:2.0.2"
3DBlobSegmentation = "sc.fiji:3D_Blob_Segmentation:3.0.1"
archipelago = "sc.fiji:Fiji_Archipelago:2.0.1"
developer = "sc.fiji:Fiji_Developer:2.0.7"
packageMaker = "sc.fiji:Fiji_Package_Maker:2.1.1"
plugins = "sc.fiji:Fiji_Plugins:3.1.1"
filamentDetector = "sc.fiji:FilamentDetector:1.0.0"
flowJ = "sc.fiji:FlowJ_:2.0.1"
graphCut = "sc.fiji:Graph_Cut:1.0.2"
grayMorphology = "sc.fiji:Gray_Morphology:2.3.5"
hDF5Vibez = "sc.fiji:HDF5_Vibez:1.1.0"
helmholtzAnalysis = "sc.fiji:Helmholtz_Analysis:2.0.2"
iJRobot = "sc.fiji:IJ_Robot:2.0.1"
iO = "sc.fiji:IO_:4.1.0"
image5D = "sc.fiji:Image_5D:2.0.2"
3DObjectsCounter = "sc.fiji:3D_Objects_Counter:2.0.1"
3DViewer = "sc.fiji:3D_Viewer:4.0.3"
imageExpressionParser = "sc.fiji:Image_Expression_Parser:3.0.1"
interactive3DSurfacePlot = "sc.fiji:Interactive_3D_Surface_Plot:3.0.0"
isoDataClassifier = "sc.fiji:IsoData_Classifier:2.0.1"
kappa = "sc.fiji:Kappa:2.0.0"
kuwaharaFilter = "sc.fiji:Kuwahara_Filter:2.0.1"
kymographBuilder = "sc.fiji:KymographBuilder:2.1.1"
lSMReader = "sc.fiji:LSM_Reader:4.1.2"
lSMToolbox = "sc.fiji:LSM_Toolbox:4.1.2"
lassoAndBlowTool = "sc.fiji:Lasso_and_Blow_Tool:2.0.2"
linearKuwahara = "sc.fiji:Linear_Kuwahara:2.0.1"
localThickness = "sc.fiji:LocalThickness_:4.0.3"
mTrack2 = "sc.fiji:MTrack2_:2.0.1"
mIP = "sc.fiji:M_I_P:2.0.1"
manualTracking = "sc.fiji:Manual_Tracking:2.1.1"
multiKymograph = "sc.fiji:Multi_Kymograph:3.0.1"
oMEVisual = "sc.fiji:OMEVisual:2.0.0"
pIVAnalyser = "sc.fiji:PIV_analyser:1.1.2"
quickPALM = "sc.fiji:QuickPALM_:1.1.2"
rATS = "sc.fiji:RATS_:2.0.2"
reconstructReader = "sc.fiji:Reconstruct_Reader:2.0.4"
sPIMOpener = "sc.fiji:SPIM_Opener:2.0.2"
sPIMRegistration = "sc.fiji:SPIM_Registration:5.0.21"
samples = "sc.fiji:Samples_:2.0.2"
seriesLabeler = "sc.fiji:Series_Labeler:2.0.1"
sioxSegmentation = "sc.fiji:Siox_Segmentation:1.0.5"
skeletonize3D = "sc.fiji:Skeletonize3D_:2.1.1"
splineDeformationGenerator = "sc.fiji:SplineDeformationGenerator_:2.0.2"
stackManipulation = "sc.fiji:Stack_Manipulation:2.1.2"
statisticalRegionMerging = "sc.fiji:Statistical_Region_Merging:2.0.1"
stitching = "sc.fiji:Stitching_:3.1.6"
syncWin = "sc.fiji:Sync_Win:1.7-fiji4"
threadKiller = "sc.fiji:Thread_Killer:2.0.1"
timeLapse = "sc.fiji:Time_Lapse:2.1.1"
timeStamper = "sc.fiji:Time_Stamper:2.1.0"
toAST = "sc.fiji:ToAST_:25.0.2"
topoJ = "sc.fiji:TopoJ_:2.0.1"
trackMate = "sc.fiji:TrackMate_:6.0.1"
trainableSegmentation = "sc.fiji:Trainable_Segmentation:3.2.34"
trakEM2Archipelago = "sc.fiji:TrakEM2_Archipelago:2.0.3"
vIBLib = "sc.fiji:VIB-lib:2.2.0"
vIB = "sc.fiji:VIB_:3.0.3"
vaa3dReader = "sc.fiji:Vaa3d_Reader:2.0.3"
vaa3dWriter = "sc.fiji:Vaa3d_Writer:1.0.3"
videoEditing = "sc.fiji:Video_Editing:2.0.1"
view5D = "sc.fiji:View5D_:2.3.1"
volumeCalculator = "sc.fiji:Volume_Calculator:2.0.2"
volumeViewer = "sc.fiji:Volume_Viewer:2.01.2"
bUnwarpJ = "sc.fiji:bUnwarpJ_:2.6.13"
bij = "sc.fiji:bij:1.0.0"
blockmatching = "sc.fiji:blockmatching_:2.1.3"
lib = "sc.fiji:fiji-lib:2.1.2"
legacyImglib1 = "sc.fiji:legacy-imglib1:1.1.9"
levelSets = "sc.fiji:level_sets:1.0.2"
palOptimization = "sc.fiji:pal-optimization:2.0.1"
panorama = "sc.fiji:panorama_:3.0.2"
registerVirtualStackSlices = "sc.fiji:register_virtual_stack_slices:3.0.5"
registration3d = "sc.fiji:registration_3d:2.0.1"
weaveJy2java = "sc.fiji:weave_jy2java:2.1.1"
 = "sc.fiji:bigwarp_fiji:6.0.0"
trakem2Tps = "sc.fiji:trakem2_tps:1.1.4"
zSpacing = "sc.fiji:z_spacing:1.1.1"
bigdataviewerCore = "sc.fiji:bigdataviewer-core:9.0.6"
bigdataviewerServer = "sc.fiji:bigdataviewer-server:3.0.0"
bigdataviewerVistools = "sc.fiji:bigdataviewer-vistools:1.0.0-beta-21"
 = "sc.fiji:bigdataviewer_fiji:6.2.0"
spimData = "sc.fiji:spim_data:2.2.4"
t2NIT = "sc.fiji:T2-NIT:1.1.3"
t2TreelineGraph = "sc.fiji:T2-TreelineGraph:1.1.3"
trakEM2 = "sc.fiji:TrakEM2_:1.3.4"
vectorString = "sc.fiji:VectorString:2.0.2"
trakem2Transform = "sc.fiji:trakem2-transform:1.0.1"
