[dependencies]
 = "org.codehaus.groovy:groovy:3.0.4"
ant = "org.codehaus.groovy:groovy-ant:3.0.4"
astbuilder = "org.codehaus.groovy:groovy-astbuilder:3.0.4"
bsf = "org.codehaus.groovy:groovy-bsf:3.0.4"
cliCommons = "org.codehaus.groovy:groovy-cli-commons:3.0.4"
cliPicocli = "org.codehaus.groovy:groovy-cli-picocli:3.0.4"
console = "org.codehaus.groovy:groovy-console:3.0.4"
datetime = "org.codehaus.groovy:groovy-datetime:3.0.4"
dateutil = "org.codehaus.groovy:groovy-dateutil:3.0.4"
docgenerator = "org.codehaus.groovy:groovy-docgenerator:3.0.4"
groovydoc = "org.codehaus.groovy:groovy-groovydoc:3.0.4"
groovysh = "org.codehaus.groovy:groovy-groovysh:3.0.4"
jaxb = "org.codehaus.groovy:groovy-jaxb:3.0.4"
jmx = "org.codehaus.groovy:groovy-jmx:3.0.4"
json = "org.codehaus.groovy:groovy-json:3.0.4"
macro = "org.codehaus.groovy:groovy-macro:3.0.4"
nio = "org.codehaus.groovy:groovy-nio:3.0.4"
servlet = "org.codehaus.groovy:groovy-servlet:3.0.4"
sql = "org.codehaus.groovy:groovy-sql:3.0.4"
swing = "org.codehaus.groovy:groovy-swing:3.0.4"
templates = "org.codehaus.groovy:groovy-templates:3.0.4"
test = "org.codehaus.groovy:groovy-test:3.0.4"
testJunit5 = "org.codehaus.groovy:groovy-test-junit5:3.0.4"
testng = "org.codehaus.groovy:groovy-testng:3.0.4"
xml = "org.codehaus.groovy:groovy-xml:3.0.4"
yaml = "org.codehaus.groovy:groovy-yaml:3.0.4"
