[dependencies]
 = "net.imagej:imagej:2.2.0"
ij = "net.imagej:ij:1.53d"
ij1Patcher = "net.imagej:ij1-patcher:1.2.0"
common = "net.imagej:imagej-common:0.34.0"
deprecated = "net.imagej:imagej-deprecated:0.1.4"
launcher = "net.imagej:imagej-launcher:6.0.1"
legacy = "net.imagej:imagej-legacy:0.37.4"
matlab = "net.imagej:imagej-matlab:0.7.4"
mesh = "net.imagej:imagej-mesh:0.8.0"
meshIo = "net.imagej:imagej-mesh-io:0.1.2"
notebook = "net.imagej:imagej-notebook:0.7.1"
omero = "net.imagej:imagej-omero:1.0.0-5.5"
omeroLegacy = "net.imagej:imagej-omero-legacy:1.0.0-5.5"
opencv = "net.imagej:imagej-opencv:0.1.1"
ops = "net.imagej:imagej-ops:0.45.5"
pluginsBatch = "net.imagej:imagej-plugins-batch:0.1.1"
pluginsCommands = "net.imagej:imagej-plugins-commands:0.8.1"
pluginsTools = "net.imagej:imagej-plugins-tools:0.3.1"
pluginsUploaderSsh = "net.imagej:imagej-plugins-uploader-ssh:0.3.2"
pluginsUploaderWebdav = "net.imagej:imagej-plugins-uploader-webdav:0.3.2"
scripting = "net.imagej:imagej-scripting:0.8.2"
server = "net.imagej:imagej-server:0.2.0"
tensorflow = "net.imagej:imagej-tensorflow:1.1.5"
uiAwt = "net.imagej:imagej-ui-awt:0.3.1"
uiSwing = "net.imagej:imagej-ui-swing:0.23.2"
updater = "net.imagej:imagej-updater:0.10.5"
opFinder = "net.imagej:op-finder:0.1.4"
