[dependencies]
annotations = "org.eclipse.jetty:jetty-annotations:9.4.29.v20200521"
client = "org.eclipse.jetty:jetty-client:9.4.29.v20200521"
continuation = "org.eclipse.jetty:jetty-continuation:9.4.29.v20200521"
deploy = "org.eclipse.jetty:jetty-deploy:9.4.29.v20200521"
http = "org.eclipse.jetty:jetty-http:9.4.29.v20200521"
httpSpi = "org.eclipse.jetty:jetty-http-spi:9.4.29.v20200521"
io = "org.eclipse.jetty:jetty-io:9.4.29.v20200521"
jaas = "org.eclipse.jetty:jetty-jaas:9.4.29.v20200521"
jaspi = "org.eclipse.jetty:jetty-jaspi:9.4.29.v20200521"
jmx = "org.eclipse.jetty:jetty-jmx:9.4.29.v20200521"
jndi = "org.eclipse.jetty:jetty-jndi:9.4.29.v20200521"
nosql = "org.eclipse.jetty:jetty-nosql:9.4.29.v20200521"
plus = "org.eclipse.jetty:jetty-plus:9.4.29.v20200521"
proxy = "org.eclipse.jetty:jetty-proxy:9.4.29.v20200521"
rewrite = "org.eclipse.jetty:jetty-rewrite:9.4.29.v20200521"
security = "org.eclipse.jetty:jetty-security:9.4.29.v20200521"
server = "org.eclipse.jetty:jetty-server:9.4.29.v20200521"
servlet = "org.eclipse.jetty:jetty-servlet:9.4.29.v20200521"
servlets = "org.eclipse.jetty:jetty-servlets:9.4.29.v20200521"
spring = "org.eclipse.jetty:jetty-spring:9.4.29.v20200521"
start = "org.eclipse.jetty:jetty-start:9.4.29.v20200521"
util = "org.eclipse.jetty:jetty-util:9.4.29.v20200521"
utilAjax = "org.eclipse.jetty:jetty-util-ajax:9.4.29.v20200521"
webapp = "org.eclipse.jetty:jetty-webapp:9.4.29.v20200521"
xml = "org.eclipse.jetty:jetty-xml:9.4.29.v20200521"
