[dependencies]
metakit = "org.openmicroscopy:metakit:5.3.2"
common = "org.openmicroscopy:ome-common:6.0.4"
poi = "org.openmicroscopy:ome-poi:5.3.3"
xml = "org.openmicroscopy:ome-xml:6.1.0"
jxrlibAll = "ome:jxrlib-all:0.2.4"
bioFormatsPlugins = "ome:bio-formats_plugins:6.5.1"
formatsApi = "ome:formats-api:6.5.1"
formatsBsd = "ome:formats-bsd:6.5.1"
formatsGpl = "ome:formats-gpl:6.5.1"
roBlitz = "org.openmicroscopy:omero-blitz:5.5.6"
roCommon = "org.openmicroscopy:omero-common:5.5.5"
roDslPlugin = "org.openmicroscopy:omero-dsl-plugin:5.5.0"
roGateway = "org.openmicroscopy:omero-gateway:5.6.3"
roModel = "org.openmicroscopy:omero-model:5.6.0"
roRenderer = "org.openmicroscopy:omero-renderer:5.5.5"
roRomio = "org.openmicroscopy:omero-romio:5.6.0"
roServer = "org.openmicroscopy:omero-server:5.5.6"
