[dependencies]
 = "io.scif:scifio:0.41.1"
bfCompat = "io.scif:scifio-bf-compat:4.1.0"
cli = "io.scif:scifio-cli:0.6.1"
hdf5 = "io.scif:scifio-hdf5:0.2.1"
jaiImageio = "io.scif:scifio-jai-imageio:1.1.1"
lifesci = "io.scif:scifio-lifesci:0.9.0"
omeXml = "io.scif:scifio-ome-xml:0.16.1"
