[dependencies]
batchProcessor = "org.scijava:batch-processor:0.4.1"
minimaven = "org.scijava:minimaven:2.2.2"
nativeLibLoader = "org.scijava:native-lib-loader:2.3.4"
parsington = "org.scijava:parsington:2.0.0"
cache = "org.scijava:scijava-cache:0.1.2"
common = "org.scijava:scijava-common:2.85.0"
config = "org.scijava:scijava-config:2.0.2"
grab = "org.scijava:scijava-grab:0.1.0"
ioHttp = "org.scijava:scijava-io-http:0.2.1"
java3d = "org.scijava:scijava-java3d:0.1.0"
listeners = "org.scijava:scijava-listeners:1.0.0-beta-3"
logSlf4j = "org.scijava:scijava-log-slf4j:1.0.5"
optional = "org.scijava:scijava-optional:1.0.0"
pluginsCommands = "org.scijava:scijava-plugins-commands:0.2.3"
pluginsIoTable = "org.scijava:scijava-plugins-io-table:0.4.0"
pluginsPlatforms = "org.scijava:scijava-plugins-platforms:0.3.1"
pluginsTextMarkdown = "org.scijava:scijava-plugins-text-markdown:0.1.3"
pluginsTextPlain = "org.scijava:scijava-plugins-text-plain:0.1.3"
search = "org.scijava:scijava-search:0.7.0"
table = "org.scijava:scijava-table:0.7.0"
uiAwt = "org.scijava:scijava-ui-awt:0.1.7"
uiSwing = "org.scijava:scijava-ui-swing:0.13.2"
scriptEditor = "org.scijava:script-editor:0.5.6"
scriptingBeanshell = "org.scijava:scripting-beanshell:0.3.4"
scriptingClojure = "org.scijava:scripting-clojure:0.1.6"
scriptingGroovy = "org.scijava:scripting-groovy:0.3.0"
scriptingJava = "org.scijava:scripting-java:0.4.1"
scriptingJavascript = "org.scijava:scripting-javascript:0.5.0"
scriptingJruby = "org.scijava:scripting-jruby:0.3.1"
scriptingJython = "org.scijava:scripting-jython:1.0.0"
scriptingKotlin = "org.scijava:scripting-kotlin:0.1.1"
scriptingMatlab = "org.scijava:scripting-matlab:0.5.2"
scriptingRenjin = "org.scijava:scripting-renjin:0.2.3"
scriptingScala = "org.scijava:scripting-scala:0.2.2"
swingCheckboxTree = "org.scijava:swing-checkbox-tree:1.0.2"
uiBehaviour = "org.scijava:ui-behaviour:2.0.3"
j3dcore = "org.scijava:j3dcore:1.6.0-scijava-2"
j3dutils = "org.scijava:j3dutils:1.6.0-scijava-2"
vecmath = "org.scijava:vecmath:1.6.0-scijava-2"
jep = "org.scijava:jep:2.4.2"
junitBenchmarks = "org.scijava:junit-benchmarks:0.7.4-scijava"
