[dependencies]
cocoaMacosx = "org.eclipse.swt:org.eclipse.swt.cocoa.macosx:4.3"
cocoaMacosxX8664 = "org.eclipse.swt:org.eclipse.swt.cocoa.macosx.x86_64:4.3"
gtkAixPpc = "org.eclipse.swt:org.eclipse.swt.gtk.aix.ppc:4.3"
gtkAixPpc64 = "org.eclipse.swt:org.eclipse.swt.gtk.aix.ppc64:4.3"
gtkHpuxIa64 = "org.eclipse.swt:org.eclipse.swt.gtk.hpux.ia64:4.3"
gtkLinuxPpc = "org.eclipse.swt:org.eclipse.swt.gtk.linux.ppc:4.3"
gtkLinuxPpc64 = "org.eclipse.swt:org.eclipse.swt.gtk.linux.ppc64:4.3"
gtkLinuxS390 = "org.eclipse.swt:org.eclipse.swt.gtk.linux.s390:4.3"
gtkLinuxS390x = "org.eclipse.swt:org.eclipse.swt.gtk.linux.s390x:4.3"
gtkLinuxX86 = "org.eclipse.swt:org.eclipse.swt.gtk.linux.x86:4.3"
gtkLinuxX8664 = "org.eclipse.swt:org.eclipse.swt.gtk.linux.x86_64:4.3"
gtkSolarisSparc = "org.eclipse.swt:org.eclipse.swt.gtk.solaris.sparc:4.3"
gtkSolarisX86 = "org.eclipse.swt:org.eclipse.swt.gtk.solaris.x86:4.3"
win32Win32X86 = "org.eclipse.swt:org.eclipse.swt.win32.win32.x86:4.3"
win32Win32X8664 = "org.eclipse.swt:org.eclipse.swt.win32.win32.x86_64:4.3"
