/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package upgraded.octo.guacamole

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'upgraded.octo.guacamole.greeting' plugin.
 */
class UpgradedOctoGuacamolePluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
//        val project = ProjectBuilder.builder().build()
//        project.plugins.apply("upgraded.octo.guacamole.greeting")
//
//        // Verify the result
//        assertNotNull(project.tasks.findByName("greeting"))
    }
}
